name=@extname@
description=Sony SPC970 processor language support with SLEIGH disassembly and p-code semantics for decompilation.
author=DiscoStarslayer
createdOn=2023-08-03
version=@extversion@
